// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsw2jJauitDegrYqfjkEmulD8LfUbM4KQ',
    appId: '1:803607607490:web:2c75d2f609a890d146235b',
    messagingSenderId: '803607607490',
    projectId: 'my-fyp-project-b904b',
    authDomain: 'my-fyp-project-b904b.firebaseapp.com',
    storageBucket: 'my-fyp-project-b904b.firebasestorage.app',
    measurementId: 'G-4TQTW4D367',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHijTjKVmQS0HpdeizY0dkXy81GM8ENaU',
    appId: '1:803607607490:ios:3125ddff2663a84d46235b',
    messagingSenderId: '803607607490',
    projectId: 'my-fyp-project-b904b',
    storageBucket: 'my-fyp-project-b904b.firebasestorage.app',
    iosBundleId: 'com.example.smartSocietyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsw2jJauitDegrYqfjkEmulD8LfUbM4KQ',
    appId: '1:803607607490:web:d5cf8634c237ae3b46235b',
    messagingSenderId: '803607607490',
    projectId: 'my-fyp-project-b904b',
    authDomain: 'my-fyp-project-b904b.firebaseapp.com',
    storageBucket: 'my-fyp-project-b904b.firebasestorage.app',
    measurementId: 'G-6TMG83BNQY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHijTjKVmQS0HpdeizY0dkXy81GM8ENaU',
    appId: '1:803607607490:ios:3125ddff2663a84d46235b',
    messagingSenderId: '803607607490',
    projectId: 'my-fyp-project-b904b',
    storageBucket: 'my-fyp-project-b904b.firebasestorage.app',
    iosBundleId: 'com.example.smartSocietyApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwexqkW9AQiIocylF0zsLcpqycjPjI8G0',
    appId: '1:803607607490:android:0670bd089bb9a30946235b',
    messagingSenderId: '803607607490',
    projectId: 'my-fyp-project-b904b',
    storageBucket: 'my-fyp-project-b904b.firebasestorage.app',
  );

}